name: signalr
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://www.example.com

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  async: ^2.10.0
  basics: ^0.9.0
  characters: ^1.2.1
  chunked_stream: ^1.4.1
  extensions: ^0.3.10
  http: ^0.13.5
  os_detect: ^2.0.1
  path: ^1.8.2
  pub_semver: ^2.1.3
  quiver: ^3.1.0
  shelf: ^1.4.0
  shelf_web_socket: ^1.0.3
  sse: ^4.1.1
  stream_channel: ^2.1.1
  uri: ^1.0.0
  web_socket_channel: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0